spring:
  application:
   name: restaurant-service
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurantdb
    username: user
    password: "{cipher}ec96c05466213eafc804842eaf1d7832afe6b706341fa25f2074cf7573743757"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

server:
  port: 9091



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


